const CATEGORY_URL_SEGMENT = "categories";
const PRODUCTS_URL_SEGMENT = "products";
const PRODUCT_DETAILS_URL_SEGMENT = "product-details";

const POSSIBLE_URL_SEGMENTS = [
  CATEGORY_URL_SEGMENT,
  PRODUCTS_URL_SEGMENT,
  PRODUCT_DETAILS_URL_SEGMENT,
];

const CATEGORY_QUERY = "categoryId";
const PRODUCT_QUERY = "productId";

export {
  POSSIBLE_URL_SEGMENTS,
  CATEGORY_URL_SEGMENT,
  PRODUCTS_URL_SEGMENT,
  PRODUCT_DETAILS_URL_SEGMENT,
  CATEGORY_QUERY,
  PRODUCT_QUERY,
};
